apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-utility-logique
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rustamapm/logique-iac.git
    targetRevision: main
    path: logique-utility
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true